name: navigation
publish_to: none
description: App router aggregator — depends on feature routes.

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.38.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  navigation_api:
    path: ../navigation_api
  shell:
    path: ../features/shell

  auto_route: ^11.1.0
  injectable: ^3.0.0

dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.7.1
  injectable_generator: ^3.0.2
