name: core
publish_to: none
description: Project core module — domain-agnostic shared kernel and technical ports.

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.38.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  async: ^2.13.0
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  injectable: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  flutter_native_splash: ^2.4.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^3.0.2
  build_runner: ^2.7.1

flutter:
  assets:
    - resources/lang/
