name: core
publish_to: none
description: Project core module

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.38.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  permission_handler: ^12.0.1
  injectable: ^3.0.0
  dev: ^1.0.0
  flutter_dotenv: ^6.0.0
  collection: ^1.19.1
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  flutter_native_splash: ^2.4.7
  add_2_calendar: ^3.0.1
  path_provider: ^2.1.5
  open_filex: ^4.5.1
  shared_preferences: ^2.5.3

  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  firebase_crashlytics: ^5.0.7

  package_info_plus: ^9.0.1
  sealed_countries: ^3.1.0
  flutter_libphonenumber: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^3.0.2
  build_runner: ^2.7.1

flutter:
  assets:
    - resources/lang/
